config/routes.rb
Rails.application.routes.draw do
  # Authentication routes
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match '/signout', to: 'sessions#destroy', via: [:get, :post]

  # Time blocks
  get 'modulos/opciones', to: 'time_blocks#options'
  resources :time_blocks, path: 'modulos'

  # Courses
  resources :courses, path: 'cursos' do
    get 'ayudantes', to: 'courses#teaching_assistants', on: :member
  end

  # Requests
  resources :requests, path: 'peticiones'

  # Confirmed classes
  # match 'clases/:id/:slug', to: 'clases#show', via: [:get]
  resources :confirmed_classes, path: 'clases', param: :'id_slug', only: [:show, :index, :destroy, :new] do
    member do
        get 'ayudantes/si', to: 'confirmed_classes#answer_teaching_assistant_yes'
        get 'ayudantes/no', to: 'confirmed_classes#answer_teaching_assistant_no'
        get 'alumnos/si', to: 'confirmed_classes#answer_student_yes'
        get 'alumnos/no', to: 'confirmed_classes#answer_student_no'
    end
  end

  # Teaching assistants
  resources :teaching_assistants, path: 'ayudantes'

  # Root
  root 'welcome#index'
end

app/models/user.rb
class User < ApplicationRecord
	has_one :identity, dependent: :destroy
	has_many :requests

	validates_presence_of :google_name
	validates_presence_of :google_email
	validates_presence_of :google_image
	validates_presence_of :google_token

	validates_inclusion_of :role, in: %i[admin teaching_assistant student]

	after_create :check_if_user_is_teaching_assistant

	def role
		self.attributes['role'].to_sym
	end

	def role?(r)
		self.role == r
	end

	def self.create_from_hash!(hash)
		create(User.google_attributes(hash))
	end

	def update_from_hash!(hash)
		update(User.google_attributes(hash))
	end

	protected

		def check_if_user_is_teaching_assistant
			user_as_ta = TeachingAssistant.find_by(email: self.google_email)
			return if user_as_ta.nil?
			self.role = :teaching_assistant
		end

	private

		def self.google_attributes(hash)
			{
				:google_name => hash['info']['name'],
				:google_email => hash['info']['email'],
				:google_image => hash['info']['image'],
				:google_token => hash['credentials']['token']
			}
		end
end

app/controllers/confirmed_classes_controller.rb
class ConfirmedClassesController < ApplicationController
  load_and_authorize_resource
  before_action :set_confirmed_class_with_slug, only: [
    :answer_teaching_assistant_yes,
    :answer_teaching_assistant_no,
    :answer_student_yes,
    :answer_student_no,
    :show,
    :destroy,
  ]

  # GET /clases/:id_slug/ayudantes/si
  def answer_teaching_assistant_yes
    # Clase exitosamente asignada -> Se envia correo a alumnos desde modelo
    @confirmed_class.update(assigned: true)
    redirect_to(@confirmed_class)
  end

  # GET /clases/:id_slug/ayudantes/no
  def answer_teaching_assistant_no
    # Clase no pudo asignarse -> Se busca un nuevo ayudante desde modelo
    @confirmed_class.destroy
    redirect_to(controller: 'welcome', action: 'index')
  end

  # GET /clases/:id_slug/alumnos/si
  def answer_student_yes
    # Clase confirmada -> Se le avisa a ayudante desde modelo
    @confirmed_class.update(confirmed: true)
    redirect_to(@confirmed_class)
  end

  # GET /clases/:id_slug/alumnos/no
  def answer_student_no
    # Actualizar contador o usar flash para mostrar el estado actual
    redirect_to(@confirmed_class)
  end

  # GET /clases
  def index
  end

  # GET /clases/:id_slug
  def show
    @teaching_assistant = @confirmed_class.teaching_assistant
  end

  # GET /clases/new
  def new
    @confirmed_class = ConfirmedClass.new
  end

  # DELETE /clases/:id_slug
  def destroy
    @confirmed_class.destroy
    redirect_to confirmed_classes_path
  end

  private
    # # Use callbacks to share common setup or constraints between actions.
    def set_confirmed_class_with_slug
      id, slug = Array.new(2).zip(params[:id_slug].split('-', 2)).transpose.last
      # Use bang version to raise RecordNotFound if needed
      @confirmed_class = ConfirmedClass.find_by!(id: id, slug: slug)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def confirmed_class_params
      params.require(:confirmed_class).permit(:teaching_assistant_id, :preference_id, request_ids: [])
    end
end

app/helpers/confirmed_classes_helper.rb
module ConfirmedClassesHelper
end

app/views/confirmed_classes/_form.html.erb
<%= form_with(model: confirmed_class, local: true) do |form| %>
  <% if confirmed_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(confirmed_class.errors.count, "error") %> prohibited this confirmed_class from being saved:</h2>

      <ul>
      <% confirmed_class.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :course %><br>
    <%= form.collection_select(:course_id, Course.all, :id, :name, {}, { id: "course", onchange: "updateFromCourseCreate();" }) %>
  </div>

  <div class="field">
    <%= form.label :preference %><br>
    <%= form.collection_select(:preference_id, {}, nil, nil) %>
  </div>

  <div class="field">
    <%= form.label :teaching_assistant %><br>
    <%= form.collection_select(:teaching_assistant_id, {}, nil, nil) %>
  </div>

  <div class="field">
    <%= form.label :requests %>
    <ul id="request-list">
    <%= form.collection_check_boxes(:request_ids, {}, nil, nil) do |request| %>
      <li><%= request.label class: "label-checkbox" do %>
        <%= request.check_box + request.text %>
      <% end %></li>
    <% end %>
    </ul>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/confirmed_classes/index.html.erb
<div class="container text-center">
    <h1 class="mt-5">Clases en proceso</h1>
    <p class="lead">Estas son las solicitudes que están siendo procesadas por el algoritmo de asignación</p>
</div>

<div class="container text-center">
    <table class="table table-striped table-dark">
        <thead>
            <tr>
                <th scope="col">Curso</th>
                <% unless current_user.role?(:teaching_assistant) %>
                <th>Ayudante</th>
                <% end %>
                <th>Fecha</th>
                <th>Solicitudes</th>
                <th>Estado</th>
                <% unless can? :manage, ConfirmedClass %>
                <th>Acciones</th>
                <% else%>
                <th colspan="2">Acciones</th>
                <% end %>
            </tr>
        </thead>
        <tbody>
            <% @confirmed_classes.each do |confirmed_class| %>
            <tr>
                <th scope="row">
                    <% if confirmed_class.course.nil? %>
                    ¯\_(ツ)_/¯
                    <% else %>
                    <%= confirmed_class.course.name %>
                    <% end %>
                </th>
                <% if confirmed_class.teaching_assistant.nil? %>
                <td>
                    Ayudante eliminado
                </td>
                <% elsif !current_user.role?(:teaching_assistant) %>
                <td>
                    <%= confirmed_class.teaching_assistant.name %>
                </td>
                <% end %>
                <td>
                    <%= confirmed_class.preference.display_preference %>
                </td>
                <td>
                    <%= confirmed_class.requests.length %>
                </td>
                <td>
                    <%= confirmed_class.display_status %>
                </td>
                <td>
                    <%= link_to 'Ver', confirmed_class %>
                </td>
                <% if can? :manage, ConfirmedClass %>
                <td>
                    <%= link_to('Eliminar', confirmed_class, method: :delete, data: { confirm: '¿Estás segur@?' }) %>
                </td>
                <% end %>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

<div class="container">
    <% if can? :new, ConfirmedClass %>
    <%= link_to('Asignar una clase (en construcción)', new_confirmed_class_path, { class: "btn btn-primary disabled" }) %>
    <% end %>
</div>

<div class="container">
    <div class="card text-white bg-info" style="width: 100%;">
        <div class="card-header">Algoritmo de asignación</div>
        <div class="card-body">
            <h5 class="card-title">Sección 1</h5>
            <p class="card-text">Descripción</p>
        </div>
    </div>
</div>

app/views/confirmed_classes/new.html.erb
<div class="container text-center">
    <h1 class="mt-5">Crea una clase</h1>
    <p class="lead">Al asignar solicitudes, se enviarán los correos automáticamente</p>
</div>

<div class="container">
    <%# render 'form', confirmed_class: @confirmed_class %>
</div>

app/views/confirmed_classes/show.html.erb
<div class="container text-center">
    <h1 class="mt-5">Clase asignada
        <%= @confirmed_class.id %>
    </h1>
    <p>Esta es una de las solicitudes que ya está siendo procesada por el algoritmo de asignación de clases</p>
</div>
<div class="container">
    <div class="row">
        <div class="card text-white bg-dark" style="width: 100%;">
            <div class="card-header">
                Asignada a <strong>
                    <%= link_to @teaching_assistant.name, @teaching_assistant %> (
                    <%= mail_to(@teaching_assistant.email) %>)</strong>
            </div>
            <div class="card-body">
                <h5 class="card-title">
                    <%= link_to(@confirmed_class.course.name, course_path(@confirmed_class.course)) %>
                </h5>
                <p class="card-text"><strong>Fecha:</strong>
                    <%= @confirmed_class.preference.display_preference %>
                </p>
                <h6 class="card-subtitle mb-2 text-muted">
                    <strong>Estado:</strong>
                    <%= @confirmed_class.display_status %>
                </h6>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="card-group" style="width: 100%;">
            <% @confirmed_class.requests.each do |request| %>
            <div class="card text-white bg-dark">
                <div class="card-body">
                    <p class="card-text"><strong>Contenidos:</strong>
                        <%= request.contents %>
                    </p>
                    <% if current_user && (current_user.role?(:admin) || @confirmed_class.confirmed) %>
                    <p>Los <strong>alumnos</strong> de esta solicitud son</p>
                    <ul>
                        <% request.participants_mails.each do |participant_email| %>
                        <li>
                            <%= mail_to(participant_email) %>
                        </li>
                        <% end %>
                    </ul>
                    <% end %>
                </div>
                <div class="card-footer">
                    <small class="text-muted">Solicitada hace
                        <%= (Time.zone.now.to_i - request.created_at.to_i) / 3600 %> horas</small>
                    <% if can? :show, request %>
                    <small><%= link_to("Ver solicitud", request, { class: "card-link" }) %></small>
                    <% end %>
                </div>
            </div>
            <% end %>
        </div>
    </div>
</div>