config/routes.rb
Rails.application.routes.draw do
  # Authentication routes
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match '/signout', to: 'sessions#destroy', via: [:get, :post]

  # Time blocks
  get 'modulos/opciones', to: 'time_blocks#options'
  resources :time_blocks, path: 'modulos'

  # Courses
  resources :courses, path: 'cursos' do
    get 'ayudantes', to: 'courses#teaching_assistants', on: :member
  end

  # Requests
  resources :requests, path: 'peticiones'

  # Confirmed classes
  # match 'clases/:id/:slug', to: 'clases#show', via: [:get]
  resources :confirmed_classes, path: 'clases', param: :'id_slug', only: [:show, :index, :destroy, :new] do
    member do
        get 'ayudantes/si', to: 'confirmed_classes#answer_teaching_assistant_yes'
        get 'ayudantes/no', to: 'confirmed_classes#answer_teaching_assistant_no'
        get 'alumnos/si', to: 'confirmed_classes#answer_student_yes'
        get 'alumnos/no', to: 'confirmed_classes#answer_student_no'
    end
  end

  # Teaching assistants
  resources :teaching_assistants, path: 'ayudantes'

  # Root
  root 'welcome#index'
end

app/models/time_block.rb
class TimeBlock < ApplicationRecord
    has_and_belongs_to_many :teaching_assistants
    has_many :preferences
    validates :day, presence: true, inclusion: {in: 1..5}
    validate :start_before_finish

    validates_uniqueness_of :start, scope: :day
    validates_uniqueness_of :finish, scope: :day

    default_scope { order(day: :asc, start: :asc) }


    def self.split_by_weekday(time_blocks, today=DateTime.now.in_time_zone)
        case today.strftime("%u").to_i
        when 6, 7
            [[], time_blocks]
        when 1
            [time_blocks, []]
        else
            today_as_i = today.strftime("%w").to_i
            cut_here = time_blocks.index{ |tb| tb.day >= today_as_i }
            case cut_here
            when 0
                [time_blocks, []]
            when time_blocks.length
                [[], time_blocks]
            else
                [
                    time_blocks.slice(cut_here..time_blocks.length),
                    time_blocks.slice(0..(cut_here - 1))
                ]
            end
        end
    end

    def self.generate_events(on_week, add_week, today=DateTime.now.in_time_zone)
        # Between 7 and 21 days (2 and 3 weeks from now)
        events = []
        # Monday is 1, we need to start from 0
        now = today.beginning_of_week - 1.day
        [1, 2].each do |w|
            on_week.each do |tb|
                events << {
                    internal_id: tb.id,
                    start: now.change({hour: tb.start.hour, min: tb.start.min}) + tb.day.days + w.weeks,
                    finish: now.change({hour: tb.finish.hour, min: tb.finish.min}) + tb.day.days + w.weeks,
                }
            end
            add_week.each do |tb|
                events << {
                    internal_id: tb.id,
                    start: now.change({hour: tb.start.hour, min: tb.start.min}) + tb.day.days + (w + 1).weeks,
                    finish: now.change({hour: tb.finish.hour, min: tb.finish.min}) + tb.day.days + (w + 1).weeks,
                }
            end
        end
        events
    end

    def available_courses
        courses_ids = teaching_assistants.joins(:courses).pluck(:course_id)
        Course.where(id: courses_ids)
    end

    def display_day
        I18n.t('date.day_names')[self[:day]]
    end

    def display_start
        self[:start].strftime("%R")
    end

    def display_finish
        self[:finish].strftime("%R")
    end

    def display_block
        "#{display_day} (#{display_start}-#{display_finish})"
    end

    private
        def start_before_finish
            errors.add(:finish, "antes de inicio") if start && finish && start >= finish
        end

end

app/controllers/time_blocks_controller.rb
class TimeBlocksController < ApplicationController
  load_and_authorize_resource

  before_action :set_time_block, only: [:show, :edit, :update, :destroy]

  def options
    course_param = params.fetch(:curso, "")
    unless course_param.empty?
      course = Course.find(course_param)
      @time_blocks = course.available_modules
    else
      @time_blocks = TimeBlock.all
    end
    on_week, add_week = TimeBlock.split_by_weekday(@time_blocks)
    @events = TimeBlock.generate_events(on_week, add_week)
  end

  # GET /time_blocks
  # GET /time_blocks.json
  def index
  end

  # GET /time_blocks/1
  # GET /time_blocks/1.json
  def show
  end

  # GET /time_blocks/new
  def new
    @time_block = TimeBlock.new
  end

  # GET /time_blocks/1/edit
  def edit
  end

  # POST /time_blocks
  # POST /time_blocks.json
  def create
    @time_block = TimeBlock.new(time_block_params)

    respond_to do |format|
      if @time_block.save
        format.js
        format.html { redirect_to @time_block, notice: 'Time block was successfully created.' }
        format.json { render :show, status: :created, location: @time_block }
      else
        format.js   { render action: :new }
        format.html { render :new }
        format.json { render json: @time_block.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_blocks/1
  # PATCH/PUT /time_blocks/1.json
  def update
    respond_to do |format|
      if @time_block.update(time_block_params)
        format.js
        format.html { redirect_to @time_block, notice: 'Time block was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_block }
      else
        format.js   { render action: :edit }
        format.html { render :edit }
        format.json { render json: @time_block.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_blocks/1
  # DELETE /time_blocks/1.json
  def destroy
    @time_block.destroy
    respond_to do |format|
      format.html { redirect_to time_blocks_url, notice: 'Time block was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_block
      @time_block = TimeBlock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def time_block_params
      params.require(:time_block).permit(:day, :start, :finish, teaching_assistant_ids: [])
    end
end

app/helpers/time_blocks_helper.rb
module TimeBlocksHelper
end

app/views/time_blocks/_form.html.erb
<%= form_with(model: time_block, remote: true) do |form| %>
    <!-- Errors explanation -->
    <% if time_block.errors.any? %>
        <%= errors_for(time_block, "este módulo") %>
    <% end %>
    <!-- Day -->
    <div class="form-group row">
        <div class="col-md-2"></div>
        <%= form.label :day, "Dia", class: "col-md-2 col-form-label text-center" %>
        <div class="col-md-6 time-select">
            <%= form.select(:day, (1..5).map {|i| [I18n.t('date.day_names')[i], i]}, {}, { class: "form-control" }) %>
        </div>
        <div class="col-md-2"></div>
    </div>
    <!-- Start -->
    <div class="form-group row">
        <div class="col-md-2"></div>
        <%= form.label :start, "Inicio", class: "col-md-2 col-form-label text-center" %>
        <div class="col-md-6 time-select">
            <%= form.time_select(:start, { prompt: {hour: 'Elegir hora', minute: 'Elegir minutos'}, minute_step: 5 }, { class: "form-control" }) %>
        </div>
        <div class="col-md-2"></div>
    </div>
    <!-- Finish -->
    <div class="form-group row">
        <div class="col-md-2"></div>
        <%= form.label :finish, "Final", class: "col-md-2 col-form-label text-center" %>
        <div class="col-md-6 time-select">
            <%= form.time_select(:finish, { prompt: {hour: 'Elegir hora', minute: 'Elegir minutos'}, minute_step: 5 }, { class: "form-control" }) %>
        </div>
        <div class="col-md-2"></div>
    </div>
    <!-- Teaching assistants -->
    <div class="form-group row">
        <div class="col-md-2"></div>
        <%= form.label :teaching_assistants, "Ayudantes", class: "col-md-2 col-form-label text-center" %>
        <div class="col-md-3">
            <%= form.collection_check_boxes(:teaching_assistant_ids, TeachingAssistant.order_by_name.first((TeachingAssistant.count/2).ceil), :id, :name, { class: "col-md-6" } ) do |ta| %>
                <div class="form-check">
                <%= ta.label(class: "form-check-label") do %>
                    <%= ta.check_box(class: "form-check-input") + ta.text %>
                <% end %>
                </div>
            <% end %>
        </div>
        <div class="col-md-3">
            <%= form.collection_check_boxes(:teaching_assistant_ids, TeachingAssistant.order_by_name.last((TeachingAssistant.count/2).floor), :id, :name, { class: "col-md-6" } ) do |ta| %>
                <div class="form-check">
                <%= ta.label(class: "form-check-label") do %>
                    <%= ta.check_box(class: "form-check-input") + ta.text %>
                <% end %>
                </div>
            <% end %>
        </div>
        <div class="col-md-2"></div>
    </div>
    <!-- Submit -->
    <div class="form-actions">
        <div class="col-auto">
            <%= button_tag(class: "btn btn-primary btn-lg") do %>
                <span class="fa fa-clock"></span> Guardar módulo
            <% end %>
        </div>
    </div>
<% end %>

app/views/time_blocks/create.js.erb
window.location = '<%= time_block_path @time_block %>';

app/views/time_blocks/edit.html.erb
<div class="container text-center">
    <h1 class="mt-5">Editar módulo</h1>
    <p class="lead">Todos los cambios que hagas se verán automáticamente reflejados en toda la plataforma</p>
</div>

<div class="container">
    <%= render 'form', time_block: @time_block %>
</div>

<div class="container">
    <%= link_to('Ver módulo', @time_block, { class: "btn btn-primary" }) %>
</div>

app/views/time_blocks/edit.js.erb
// Render new form (with errors)
Rails.$('form')[0].innerHTML = ("<%= j(render partial: 'form', locals: { time_block: @time_block }) %>");
// Scroll to top
window.scrollTo({ top: 0, behavior: 'smooth' });

app/views/time_blocks/index.html.erb
<div class="container text-center">
    <h1 class="mt-5">Modulos disponibles</h1>
    <p class="lead">Las clases se pueden pedir y realizar en los siguientes módulos</p>
</div>

<div class="container text-center">
    <table class="table table-striped table-dark">
        <thead>
            <tr>
                <th scope="col">Dia</th>
                <th>Inicio</th>
                <th>Término</th>
                <th colspan="3">Acciones</th>
            </tr>
        </thead>
        <tbody>
            <% @time_blocks.each do |time_block| %>
            <tr>
                <th scope="row">
                    <%= time_block.display_day %>
                </th>
                <td>
                    <%= time_block.display_start %>
                </td>
                <td>
                    <%= time_block.display_finish %>
                </td>
                <td>
                    <%= link_to('Ver', time_block) %>
                </td>
                <td>
                    <%= link_to('Editar', edit_time_block_path(time_block)) %>
                </td>
                <td>
                    <%= link_to('Eliminar', time_block, method: :delete, data: { confirm: '¿Estás segur@?' }) %>
                </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

<div class="container">
    <% if can? :new, TimeBlock %>
        <%= link_to('Agregar módulo', new_time_block_path, { class: "btn btn-primary" }) %>
    <% end %>
</div>

app/views/time_blocks/new.html.erb
<div class="container text-center">
    <h1 class="mt-5">Agrega un módulo</h1>
    <p class="lead">Al agregar un nuevo módulo, quedará automáticamente disponible en toda la plataforma</p>
</div>

<div class="container">
    <%= render 'form', time_block: @time_block %>
</div>

app/views/time_blocks/new.js.erb
// Render new form (with errors)
Rails.$('form')[0].innerHTML = ("<%= j(render partial: 'form', locals: { time_block: @time_block }) %>");
// Scroll to top
window.scrollTo({ top: 0, behavior: 'smooth' });

app/views/time_blocks/show.html.erb
<div class="container text-center">
    <h1 class="mt-5"><%= @time_block.display_block %></h1>
    <p class="lead">El mejor momento posible para hacer una clase de GoIng</p>
</div>

<div class="container">
    <div class="row">
        <div class="col">
            <p><strong>Ayudantes</strong> que pueden hacer una clase en este módulo</p>
            <ul>
                <% @time_block.teaching_assistants.each do |teaching_assistant| %>
                <li>
                    <%= link_to(teaching_assistant.name, teaching_assistant) %>
                </li>
                <% end %>
            </ul>
        </div>
        <div class="col">
            <p>Los <strong>cursos</strong> que están disponibles este módulo<p>
            <ul>
                <% @time_block.available_courses.each do |course| %>
                <li>
                    <%= link_to course.name, course_path(course) %>
                </li>
                <% end %>
            </ul>
        </div>
    </div>
</div>

<div class="container">
    <% if can? :edit, @time_block %>
    <%= link_to('Editar módulo', edit_time_block_path(@time_block), { class: "btn btn-primary" }) %>
    <% end %>
</div>

app/views/time_blocks/update.js.erb
window.location = '<%= time_block_path @time_block %>';