config/routes.rb
Rails.application.routes.draw do
  # Authentication routes
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match '/signout', to: 'sessions#destroy', via: [:get, :post]

  # Time blocks
  get 'modulos/opciones', to: 'time_blocks#options'
  resources :time_blocks, path: 'modulos'

  # Courses
  resources :courses, path: 'cursos' do
    get 'ayudantes', to: 'courses#teaching_assistants', on: :member
  end

  # Requests
  resources :requests, path: 'peticiones'

  # Confirmed classes
  # match 'clases/:id/:slug', to: 'clases#show', via: [:get]
  resources :confirmed_classes, path: 'clases', param: :'id_slug', only: [:show, :index, :destroy, :new] do
    member do
        get 'ayudantes/si', to: 'confirmed_classes#answer_teaching_assistant_yes'
        get 'ayudantes/no', to: 'confirmed_classes#answer_teaching_assistant_no'
        get 'alumnos/si', to: 'confirmed_classes#answer_student_yes'
        get 'alumnos/no', to: 'confirmed_classes#answer_student_no'
    end
  end

  # Teaching assistants
  resources :teaching_assistants, path: 'ayudantes'

  # Root
  root 'welcome#index'
end

app/models/teaching_assistant.rb
class TeachingAssistant < ApplicationRecord
  	has_many :confirmed_classes
  	has_and_belongs_to_many :courses
  	has_and_belongs_to_many :time_blocks
	has_and_belongs_to_many :unavailable_preferences,
							class_name: "Preference",
							join_table: "preferences_teaching_assistants",
							foreign_key: "preference_id",
							association_foreign_key: "teaching_assistant_id"
  	validates :name, presence: true, length: { minimum: 5 }
	validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP } 
	validates :phone_number, presence: true, numericality: true, length: { minimum: 8, maximum: 12 }
	after_create :check_if_teaching_assistant_is_user
	after_destroy :switch_back_teaching_assistant_to_user

	def self.order_by_name
		order(name: :asc)
	end

	def self.unassigned_at(course, preference)
		# TAs of this course with this time block available
	    a = course.teaching_assistants
	    b = preference.time_block.teaching_assistants
	    c = a & b
	    # Remove TAs with this preference not available
	    d = preference.unavailable_tas
	    e = c - d | d - c
	    # Sort TAs according to their assigned classes
	    f = self.left_joins(:confirmed_classes).group(:id).order(Arel.sql("COUNT(confirmed_classes.id) ASC"))
	    g = f & a
	    # Final list
	    h = g & e
	end

	protected

		def check_if_teaching_assistant_is_user
			ta_as_user = User.find_by(google_email: self.email)
			return if ta_as_user.nil?
			ta_as_user.update(role: :teaching_assistant)
		end

		def switch_back_teaching_assistant_to_user
			ta_as_user = User.find_by(google_email: self.email)
			return if ta_as_user.nil?
			ta_as_user.update(role: :student)
		end
end

app/controllers/teaching_assistants_controller.rb
class TeachingAssistantsController < ApplicationController
  load_and_authorize_resource

  before_action :set_teaching_assistant, only: [:show, :edit, :update, :destroy]

  # GET /teaching_assistants
  # GET /teaching_assistants.json
  def index
    @teaching_assistants = TeachingAssistant.all
  end

  # GET /teaching_assistants/1
  # GET /teaching_assistants/1.json
  def show
    @ta_as_user = User.find_by(google_email: @teaching_assistant.email)
  end

  # GET /teaching_assistants/new
  def new
    @teaching_assistant = TeachingAssistant.new
  end

  # GET /teaching_assistants/1/edit
  def edit
  end

  # POST /teaching_assistants
  # POST /teaching_assistants.json
  def create
    @teaching_assistant = TeachingAssistant.new(teaching_assistant_params)

    respond_to do |format|
      if @teaching_assistant.save
        format.js
        format.html { redirect_to @teaching_assistant, notice: 'Teaching assistant was successfully created.' }
        format.json { render :show, status: :created, location: @teaching_assistant }
      else
        format.js   { render action: :new }
        format.html { render :new }
        format.json { render json: @teaching_assistant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teaching_assistants/1
  # PATCH/PUT /teaching_assistants/1.json
  def update
    respond_to do |format|
      if @teaching_assistant.update(teaching_assistant_params)
        format.js
        format.html { redirect_to @teaching_assistant, notice: 'Teaching assistant was successfully updated.' }
        format.json { render :show, status: :ok, location: @teaching_assistant }
      else
        format.js   { render action: :edit }
        format.html { render :edit }
        format.json { render json: @teaching_assistant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teaching_assistants/1
  # DELETE /teaching_assistants/1.json
  def destroy
    @teaching_assistant.destroy
    respond_to do |format|
      format.html { redirect_to teaching_assistants_url, notice: 'Teaching assistant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teaching_assistant
      @teaching_assistant = TeachingAssistant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teaching_assistant_params
      params.require(:teaching_assistant).permit(:name, :email, :phone_number, course_ids: [], time_block_ids: [])
    end
end

app/helpers/teaching_assistants_helper.rb
module TeachingAssistantsHelper
end

app/views/teaching_assistants/_form.html.erb
<%= form_with(model: teaching_assistant, remote: true) do |form| %>
    <!-- Errors explanation -->
    <% if teaching_assistant.errors.any? %>
        <%= errors_for(teaching_assistant, "tu petición") %>
    <% end %>
    <!-- Name -->
    <div class="form-group row">
        <div class="col-md-2"></div>
        <%= form.label :name, "Nombre", class: "col-md-2 col-form-label text-center" %>
        <div class="col-md-6">
            <%= form.text_field(:name, { class: "form-control", placeholder: "Nombre ayudante" }) %>
        </div>
        <div class="col-md-2"></div>
    </div>
    <!-- Email -->
    <div class="form-group row">
        <div class="col-md-2"></div>
        <%= form.label :email, "Correo", class: "col-md-2 col-form-label text-center" %>
        <div class="col-md-6">
            <%= form.email_field(:email, { class: "form-control", placeholder: "Correo ayudante" }) %>
        </div>
        <div class="col-md-2"></div>
    </div>
    <!-- Phone number -->
    <div class="form-group row">
        <div class="col-md-2"></div>
        <%= form.label :phone_number, "Celular", class: "col-md-2 col-form-label text-center" %>
        <div class="col-md-6">
            <%= form.telephone_field(:phone_number, { class: "form-control", placeholder: "Celular ayudante" }) %>
        </div>
        <div class="col-md-2"></div>
    </div>
    <!-- Courses -->
    <div class="form-group row">
        <div class="col-md-2"></div>
        <%= form.label :courses, "Cursos", class: "col-md-2 col-form-label text-center" %>
        <div class="col-md-6">
            <%= form.collection_check_boxes(:course_ids, Course.all, :id, :name, { class: "col-md-6" } ) do |course| %>
                <div class="form-check">
                <%= course.label(class: "form-check-label") do %>
                    <%= course.check_box(class: "form-check-input") + course.text %>
                <% end %>
                </div>
            <% end %>
        </div>
        <div class="col-md-2"></div>
    </div>
    <!-- Time blocks -->
    <div class="form-group row">
        <div class="col-md-2"></div>
        <%= form.label :time_blocks, "Módulos", class: "col-md-2 col-form-label text-center" %>
        <div class="col-md-6">
            <%= form.collection_check_boxes(:time_block_ids, TimeBlock.all, :id, :display_block, { class: "col-md-6" } ) do |tb| %>
                <div class="form-check">
                <%= tb.label(class: "form-check-label") do %>
                    <%= tb.check_box(class: "form-check-input") + tb.text %>
                <% end %>
                </div>
            <% end %>
        </div>
        <div class="col-md-2"></div>
    </div>
    <!-- Submit -->
    <div class="form-actions">
        <div class="col-auto">
            <%= button_tag(class: "btn btn-primary btn-lg") do %>
            <span class="fa fa-glasses"></span> Guardar ayudante
            <% end %>
        </div>
    </div>
<% end %>

app/views/teaching_assistants/create.js.erb
window.location = '<%= teaching_assistant_path @teaching_assistant %>';

app/views/teaching_assistants/edit.html.erb
<div class="container text-center">
    <h1 class="mt-5">Editar ayudante</h1>
    <p class="lead">Todos los cambios que hagas se verán automáticamente reflejados en toda la plataforma</p>
</div>

<div class="container">
    <%= render 'form', teaching_assistant: @teaching_assistant %>
</div>

<div class="container">
    <%= link_to('Ver ayudante', @teaching_assistant, { class: "btn btn-primary" }) %>
</div>

app/views/teaching_assistants/edit.js.erb
// Render new form (with errors)
Rails.$('form')[0].innerHTML = ("<%= j(render partial: 'form', locals: { teaching_assistant: @teaching_assistant }) %>");
// Scroll to top
window.scrollTo({ top: 0, behavior: 'smooth' });

app/views/teaching_assistants/index.html.erb
<div class="container text-center">
    <h1 class="mt-5">Ayudantes</h1>
    <p class="lead">Este es el equipo con el que contamos para este semestre</p>
</div>

<div class="container text-center">
    <table class="table table-striped table-dark">
        <thead>
            <tr>
                <th scope="col">Nombre</th>
                <th>Correo</th>
                <% if current_user.role?(:admin) %>
                <th>Celular</th>
                <th colspan="3">Acciones</th>
                <% end %>
            </tr>
        </thead>
        <tbody>
            <% @teaching_assistants.each do |teaching_assistant| %>
            <tr>
                <% if can? :show, TeachingAssistant %>
                <th scope="row">
                    <%= link_to(teaching_assistant.name, teaching_assistant) %>
                </th>
                <% else %>
                <th scope="row">
                    <%= teaching_assistant.name %>
                </th>
                <% end %>
                <td>
                    <%= teaching_assistant.email %>
                </td>
                <% if current_user.role?(:admin) %>
                <td>
                    <%= number_to_phone(teaching_assistant.phone_number, delimiter: " ") %>
                </td>
                <td>
                    <%= link_to('Editar', edit_teaching_assistant_path(teaching_assistant)) %>
                </td>
                <td>
                    <%= link_to('Eliminar', teaching_assistant, method: :delete, data: { confirm: '¿Estás segur@?' }) %>
                </td>
                <% end %>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

<div class="container">
    <% if can? :new, TeachingAssistant %>
        <%= link_to('Agregar ayudante', new_teaching_assistant_path, { class: "btn btn-primary" }) %>
    <% end %>
</div>

app/views/teaching_assistants/new.html.erb
<div class="container text-center">
    <h1 class="mt-5">Agrega un ayudante</h1>
    <p class="lead">Al agregar un nuevo ayudante, podrás asignarlo a cualquier curso y quedará automáticamente disponible para asignarle clases</p>
</div>

<div class="container">
    <%= render 'form', teaching_assistant: @teaching_assistant %>
</div>

app/views/teaching_assistants/new.js.erb
// Render new form (with errors)
Rails.$('form')[0].innerHTML = ("<%= j(render partial: 'form', locals: { teaching_assistant: @teaching_assistant }) %>");
// Scroll to top
window.scrollTo({ top: 0, behavior: 'smooth' });

app/views/teaching_assistants/show.html.erb
<div class="container text-center">
    <h1 class="mt-5">
        <%= @teaching_assistant.name %>
    </h1>
    <p class="lead">Parte de nuestro equipo de ayudantes motivados</p>
</div>

<div class="container text-center">
    <div class="row">
        <div class="col">
            <div class="card bg-dark mx-auto" style="width: 18rem;">
                <% unless @ta_as_user.nil? %>
                <%= image_tag(@ta_as_user.google_image, class: "img-circle img-fluid img-responsive img-thumbnail card-img-top", alt: "Foto ayudante") %>
                <% else %>
                <%= image_tag("logo_ig.jpg", class: "img-circle img-fluid img-responsive img-thumbnail card-img-top", alt: "Foto ayudante") %>
                <% end %>
                <div class="card-body">
                    <p><%= @teaching_assistant.name %></p>
                    <p class="card-text"><strong>Email:</strong>
                        <%= mail_to(@teaching_assistant.email) %>
                    </p>
                    <% if current_user.role?(:admin) || current_user.google_email == @teaching_assistant.email %>
                    <p class="card-text"><strong>Phone number:</strong>
                        <%= number_to_phone(@teaching_assistant.phone_number, delimiter: " ") %>
                        <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col">
            <p><strong>Cursos</strong> en los que puede ayudar</p>
            <ul>
                <% @teaching_assistant.courses.each do |course| %>
                <li>
                    <%= link_to course.name, course_path(course) %>
                </li>
                <% end %>
            </ul>
        </div>
        <% if current_user.role?(:admin) || current_user.google_email == @teaching_assistant.email %>
        <div class="col">
            <p>Los <strong>módulos</strong> en los que puede ayudar<p>
            <ul>
                <% @teaching_assistant.time_blocks.each do |time_block| %>
                <% if can? :show, TimeBlock %>
                <li>
                    <%= link_to time_block.display_block, time_block_path(time_block) %>
                </li>
                <% else %>
                <li>
                    <%= time_block.display_block %>
                </li>
                <% end %>
                <% end %>
            </ul>
        </div>
        <% end %>
    </div>
</div>

<div class="container">
    <% if current_user.google_email == @teaching_assistant.email %>
    <%= link_to('Mis asignaciones', confirmed_classes_path, { class: "btn btn-primary" }) %>
    <% end %>
    <% if can? :edit, @teaching_assistant %>
    <%= link_to('Editar ayudante', edit_teaching_assistant_path(@teaching_assistant), { class: "btn btn-primary" }) %>
    <% end %>
</div>

app/views/teaching_assistants/update.js.erb
window.location = '<%= teaching_assistant_path @teaching_assistant %>';