config/routes.rb
Rails.application.routes.draw do
  # Authentication routes
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match '/signout', to: 'sessions#destroy', via: [:get, :post]

  # Time blocks
  get 'modulos/opciones', to: 'time_blocks#options'
  resources :time_blocks, path: 'modulos'

  # Courses
  resources :courses, path: 'cursos' do
    get 'ayudantes', to: 'courses#teaching_assistants', on: :member
  end

  # Requests
  resources :requests, path: 'peticiones'

  # Confirmed classes
  # match 'clases/:id/:slug', to: 'clases#show', via: [:get]
  resources :confirmed_classes, path: 'clases', param: :'id_slug', only: [:show, :index, :destroy, :new] do
    member do
        get 'ayudantes/si', to: 'confirmed_classes#answer_teaching_assistant_yes'
        get 'ayudantes/no', to: 'confirmed_classes#answer_teaching_assistant_no'
        get 'alumnos/si', to: 'confirmed_classes#answer_student_yes'
        get 'alumnos/no', to: 'confirmed_classes#answer_student_no'
    end
  end

  # Teaching assistants
  resources :teaching_assistants, path: 'ayudantes'

  # Root
  root 'welcome#index'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class="container">
        <span class="text-muted">Creado por <a href="http://github.com/aaossa/">Antonio Ossa</a> con <i class="fa fa-heart"></i> para Proyecto GoIng.</span>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container">
            <%= link_to root_path, class: "navbar-brand" do %>
                <span>Proyecto <b>GoIng</b></span>
            <% end %>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <% if Rails.env.development? %>
                        <span class="navbar-text text-info">
                            Development (<%= current_user.nil? ? "No role" : current_user.role %>)
                        </span>
                    <% end %>
                    <li class="nav-item">
                        <%= link_to('Cursos', { controller: 'courses' }, { class: "nav-link" }) %>
                    </li>
                    <% if signed_in? %>
                    <li class="nav-item dropdown">
                        <%= link_to("#", { class: "nav-link dropdown-toggle", id: "navbardrop", 'data-toggle':"dropdown" }) do %>
                            Clases
                        <% end %>
                        <div class="dropdown-menu">
                            <% if can? :new, Request %>
                                <%= link_to('Pedir una clase', new_request_path, { class: "dropdown-item" }) %>
                            <% end %>
                            <% if can? :index, Request %>
                                <%= link_to('Ver peticiones', { controller: 'requests' }, { class: "dropdown-item" }) %>
                            <% end %>
                            <% if can? :index, ConfirmedClass %>
                                <%= link_to('Ver clases', { controller: 'confirmed_classes' }, { class: "dropdown-item" }) %>
                            <% end %>
                        </div>
                    </li>
                    <% end %>
                    <% if can? :index, TeachingAssistant %>
                        <%= link_to('Ayudantes', { controller: 'teaching_assistants' }, { class: "nav-link" }) %>
                    <% end %>
                    <% if can? :index, TimeBlock %>
                        <%= link_to('Módulos', { controller: 'time_blocks' }, { class: "nav-link" }) %>
                    <% end %>
                </ul>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <% if signed_in? %>
                            <%= link_to(signout_path, { class: "nav-link", disabled: true}) do %>
                                Salir (<%= current_user.google_email %>)
                            <% end %>
                        <% else %>
                            <%= link_to("/auth/google", { class: "nav-link",  method: :post }) do %>
                                <span class="fa fa-google"></span> Ingresa con Google
                            <% end %>
                        <% end %>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Going</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag params[:controller], 'data-turbolinks-track': 'reload' %>
</head>

<body class="<%= params[:action] %>">
    <!-- Improve notices -->
    <p id="notice"><%= notice %></p>
    <%= render 'layouts/header' %>
    <main role="main" class="container">
        <div class="container">
            <%= yield %>
        </div>
    </main>
    <%= render 'layouts/footer' %>
</body>

</html>